### ISSUE TITLE
📝 To-Do (Hugo)

### ISSUE THREAD

**Issue by jakejarvis** [jakejarvis/jarv.is#11]
- [x] add reference to npm module in dark mode post: https://jarvis-l3fptkdan-jakejarvis.vercel.app/notes/dark-mode/
- [ ] throw error if {{< image >}} is used on non-local resource
- [ ] edge-to-edge images on mobile view
- [ ] taxonomy list pages for post tags
- [ ] ~~algolia search (#50)~~ public algolia search box
- [x] 404 page w/ main layout
- [x] header anchor links (chain symbol on hover like GitHub markdown)
- [x] add loading indicator to https://jarv.is/projects/ — like the hit counter spinner: https://github.com/jakejarvis/jarv.is/blob/034babd9af7af735c146a1b52a50cea0bb07788a/assets/sass/components/_animation.scss#L20-L42
- [x] ~~sticky nav bar~~
- [x] theme color options in `config.toml`
- [x] redo syntax highlighting colors from scratch
- [x] **dark mode** ~~(without JS ideally?)~~
- [x] native hugo nav menu config
- [x] add `netlify dev --live` script to `package.json` with proper `baseURL`
- [x] uses page https://kentcdodds.com/uses/ https://github.com/wesbos/awesome-uses
- [x] extract copy & pasted image resize logic from shortcodes/headers https://gohugo.io/templates/partials/#returning-a-value-from-a-partial
- [x] allow HTML in image captions
- [x] https://gohugo.io/templates/shortcode-templates/#checking-for-existence
- [x] https://gohugo.io/functions/path.join/
- [x] switch AMP font to ~~Roboto~~ Inter
- [x] background color for footer? (swap bg of whole `<body>` to gray, bg of `<main>` to white)
- [x] line numbers in code blocks (requires messing with tables) https://gohugo.io/getting-started/configuration-markup/#highlight
- [x] JSON keywords: extract string generation
- [x] templates: switch `if`s to `with`s
- [x] fix HR top/bottom margins
- [x] AMP video fallback message always shows
- [x] h-card -> json schema
- [x] add og:image width and height meta tags
- [x] fix logo padding on video pages
- [x] look into AMP
- [x] safe HTML on rss feed
- [x] open graph timestamp
- [x] noindex on non-pages? or remove from sitemap.xml? (/notes)
- [x] ~~match syntax highlighting on AMP pages with regular light mode color scheme~~

---

### ambitious:

- [ ] release theme as independent repo
