### ISSUE TITLE
📝 To-Do (Next.js)

### ISSUE THREAD

**Issue by jakejarvis** [jakejarvis/jarv.is#714]
...continued from #11 

- [ ] copy button tooltip
- [ ] view counts on /notes/
- [ ] full post text in rss/atom feeds
- [ ] /stats should be a table form of /api/hits
- [ ] copy button tooltip
- [ ] proper type comments
- [ ] draft option in front matter
- [ ] pagination
- [ ] port hugo image size logic https://github.com/jakejarvis/jarv.is/blob/v4/layouts/partials/functions/optimize-image.html
- [x] linked inline code isn't blue
- [x] 404 page
- [x] linkable images
- [x] /stats page
- [x] code block line numbers
- [x] extra padding on right side of code blocks (for copy button)
- [x] sentry/nextjs https://github.com/vercel/next.js/tree/canary/examples/with-sentry
- [x] research react -> preact in production??? https://github.com/preactjs/next-plugin-preact
- [x] [formik](https://github.com/jaredpalmer/formik) for contact form
- [x] `useTheme()` hook - https://github.com/primer/react/blob/main/src/ThemeProvider.tsx
- [x] `code` in post titles
- [x] menu icon spacing on mobile
- [x] #717
- [x] #715
- [x] RSS feed / sitemap
- [x] API JS to TS
- [x] group notes list by year
